services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
    volumes:
      - ./bind9/zones:/var/lib/bind
      - type: bind
        source: ./bind9/named.conf
        target: /etc/bind9/named.conf
    restart: unless-stopped

  pihole:
    image: pihole/pihole:2024.07.0
    container_name: pihole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "7053:53/tcp"
      - "7053:53/udp"
      - "7067:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "7080:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      WEBPASSWORD: geheim
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc:/etc/pihole'
      - './pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped