---
- name: Copy files
  ansible.builtin.copy:
    src: files/
    dest: /srv/traefik/
    owner: 1000
    group: 1000
    mode: 0755

- name: Copy secret
  ansible.builtin.copy:
    content: "{{ traefik_cf_dns_api_token }}"
    dest: /srv/traefik/secrets/cf_dns_api_token.secret
    owner: 1000
    group: 1000
    mode: 0600

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /srv/traefik/docker-compose.yml
    owner: 1000
    group: 1000
    mode: 0644

- name: Start portainer
  community.docker.docker_compose_v2:
    project_src: /srv/traefik
