---
- name: Copy files
  ansible.builtin.copy:
    src: files/
    dest: /srv/pihole/
    owner: 1000
    group: 1000
    mode: 0755
    force: false

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /srv/pihole/docker-compose.yml
    owner: 1000
    group: 1000
    mode: 0644

- name: Start pihole
  community.docker.docker_compose_v2:
    project_src: /srv/pihole