---
- name: Common role
  hosts: 
    - all
  become: true
  roles:
    - common

- name: Admin role
  hosts: 
    - admin
  become: true
  roles:
    - admin

- name: Docker role
  hosts:
    - admin 
    - infra
  become: true
  roles:
    - docker

