---
- name: Group admin 
  hosts: 
  - admin
  become: true
  roles:
  - common
  - admin
  - docker

- name: Group infra
  hosts:
  - infra
  become: true
  roles:
  - common
  - docker
  - traefik
  - portainer

